[workspace]
authors = ["Emma Powers <emma@emmaponders.com>"]
channels = ["conda-forge"]
name = "fpga"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
cocotb = ">=2.0.0,<3"
pytest = ">=8.4.2,<9"
verilator = ">=5.34,<6"
bitstring = ">=4.3.1,<5"
ipython = ">=9.6.0,<10"
click = ">=8.3.0,<9"
hatchling = ">=1.20"

[pypi-dependencies]
vproj = { path = "scripts/vproj", editable = true }
